/*  File: msg.c
 *  Author: Auto-generated by mkqueue.py
 */

#include "msg.h"

// ============================= Private Typedefs ==============================
typedef struct {
  uint8_t pIn;
  uint8_t pOut;
  uint8_t full;
  msg_t queue[MSG_QUEUE_ITEMS];
} msg_queue_t;

// ============================= Private Variables =============================
static msg_queue_t msg_queue;

// =========================== Function Definitions ============================
void MSGQUEUE_Init(void) {
  msg_queue.pIn = 0;
  msg_queue.pOut = 0;
  msg_queue.full = 0;
  return;
}

uint8_t MSGQUEUE_Add(msg_t *item) {
  // If full, return error
  if (msg_queue.full) {
    return MSG_QUEUE_FULL;
  }
  // Copy item into queue
  for (int n = 0; n < sizeof(msg_t); n++) {
    *((uint8_t *)&(msg_queue.queue[msg_queue.pIn]) + n) = *((uint8_t *)item + n);
  }
  // Wrap pIn at boundary
  if (msg_queue.pIn == MSG_QUEUE_ITEMS - 1) {
    msg_queue.pIn = 0;
  } else {
    msg_queue.pIn++;
  }
  // Check for full condition
  if (msg_queue.pIn == msg_queue.pOut) {
    msg_queue.full = 1;
  }
  return MSG_QUEUE_OK;
}

uint8_t MSGQUEUE_Get(volatile msg_t *item) {
  // Check for empty queue
  if ((msg_queue.pIn == msg_queue.pOut) && (msg_queue.full == 0)) {
    return MSG_QUEUE_EMPTY;
  }
  // Copy next data from the queue to item
  for (int n = 0; n < sizeof(msg_t); n++) {
    *((uint8_t *)item + n) = *((uint8_t *)&(msg_queue.queue[msg_queue.pOut]) + n);
  }
  // Wrap pOut at boundary
  if (msg_queue.pOut == MSG_QUEUE_ITEMS - 1) {
    msg_queue.pOut = 0;
  } else {
    msg_queue.pOut++;
  }
  // Clear full condition
  msg_queue.full = 0;
  return MSG_QUEUE_OK;
}

uint8_t MSGQUEUE_Status(void) {
  if ((msg_queue.pIn == msg_queue.pOut) && (msg_queue.full == 0)) {
    return MSG_QUEUE_EMPTY;
  }
  if (msg_queue.full) {
    return MSG_QUEUE_FULL;
  }
  // If not full or empty, it is non-empty (at least one item in queue)
  return MSG_QUEUE_OK;
}

