/*  file: test.h
 *  Author: Auto-generated by mkqueue.py
 */

#ifndef __TEST_H
#define __TEST_H

#ifdef __cplusplus
extern "C" {
#endif

// ================================= Includes ==================================
#include <stdio.h>

// ============================== Exported Macros ==============================
#define PUPPY_QUEUE_ITEMS                             (8)
#define PUPPY_QUEUE_OK                             (0x00)
#define PUPPY_QUEUE_FULL                           (0x01)
#define PUPPY_QUEUE_EMPTY                          (0x02)

// ============================= Exported Typedefs =============================
// Modify this definition to fit your application
typedef uint8_t puppy_t;

// ======================= Exported Function Prototypes ========================
void PUPPYQUEUE_Init(void);
uint8_t PUPPYQUEUE_Add(puppy_t *item);
uint8_t PUPPYQUEUE_Get(volatile puppy_t *item);
uint8_t PUPPYQUEUE_Status(void);

#ifdef __cplusplus
}
#endif

#endif // __TEST_H

